### ISSUE TITLE
v1.70 does not provide build_boost.v1.70.0.jl

### ISSUE THREAD

**Issue by kalmarek** [benlorenz/boostBuilder#1]

**Comment by benlorenz** [comment]
please be patient, travis is still running (20 min per arch): https://travis-ci.com/benlorenz/boostBuilder/builds/110106460

I had to delete the previous build because it contained an invalid LibraryProduct statement, libboost_signals.so was removed between 1.67 and 1.70.

**Comment by kalmarek** [comment]
ok, I thought release is made visible when everything has been built

**Comment by benlorenz** [comment]
Usually everything is uploaded together at the end, but in this case I had to split the job because of the timelimit. I think it would be possible to tell travis to create a draft release and then publish it manually afterwards, but I dont think this is necessary here.

**Comment by kalmarek** [comment]
yes, it's just a bad timing ;-)
